version: "3.9"

services:
  api:
    build: .
    container_name: visual-product-search-api
    ports:
      - "8002:8002"
    env_file:
      - .env
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8002

  ui:
    build: .
    container_name: visual-product-search-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api